# Generated by Django 3.2.7 on 2024-02-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_product'),
        ('userapp', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.product'),
        ),
    ]
