# Generated by Django 3.2.7 on 2024-02-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_product'),
        ('userapp', '0004_review_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=250)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.userdetails')),
            ],
        ),
    ]
