# Generated by Django 3.2.7 on 2024-02-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_carttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttotal',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
