# Generated by Django 3.2.7 on 2024-02-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_carttotal_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_mode',
        ),
    ]
