# Generated by Django 3.2.7 on 2024-02-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_payment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
