# Generated by Django 3.2.7 on 2024-02-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_payment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttotal',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.cart'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.carttotal'),
        ),
    ]
