# Generated by Django 3.2.7 on 2024-02-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_auto_20240219_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttotal',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.cart'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.carttotal'),
        ),
    ]
