# Generated by Django 3.2.7 on 2024-02-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_auto_20240219_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartTotal',
        ),
    ]
