# Generated by Django 3.2.7 on 2024-02-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_product'),
        ('userapp', '0017_delete_carttotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('total', models.IntegerField(null=True)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.userdetails')),
            ],
        ),
    ]
